backup:
	rm -rf requierments.txt
	pip freeze > requierments.txt

reboot:
	rm -rf .pitcoin/blockchain
	rm -rf .pitcoin/mempool

testing:
	@echo Executing tests
	@python test.py

win:
	@echo .pitcoin\pitcoinenv\Scripts\activate